archivos/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns=[
    path('nuevo/',login_required(nuevo_archivo.as_view()),name='nuevo_archivo'),
]

cenicilla/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from usuarios.views import Login,logoutUser
from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/',include(('usuarios.urls','usuarios'))),
    path('entrenamiento/',include(('entrenamiento.urls','entrenamiento'))),
    path('archivos/',include(('archivos.urls','archivos'))),
    path('foro/',include(('foro.urls','foro'))),
    path('analisis/',include(('analisis.urls','analisis'))),
    path('red_neuronal/',include(('red_neuronal.urls','red_neuronal'))),
    #urls del sistema
    path('accounts/login/',Login.as_view(),name='login'),
    path('logout/',login_required(logoutUser),name='logout'),
    #path('accounts/',include('django.contrib.auth.urls'))template_name='registration/password_reset_form.html',
    path('reset_password/',views.PasswordResetView.as_view(),name='reset_password'),
    path('reset_password_sent/',views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset_password_complete',views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('cambiar_pass',views.PasswordChangeView.as_view(),name='cambiar')
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

entrenamiento/forms.py
from django import forms
from .models import *

canales_status=[
    (1,'L'),
    (2,'A'),
    (3,'B'),
    (4,'H'),
    (5,'S'),
    (6,'V')
]

class N_ref(forms.Form):#form para la imagen de referencia 
    nombre=forms.CharField(max_length=30,widget=forms.TextInput(attrs={
    'class': 'form-control ' , 'placeholder': 'Nombre'}))
    img_ref=forms.ImageField()
    #img_ref.widget.attrs.update({'class':'btn btn-primary'})

class Datos(forms.Form):
    nombre=forms.CharField(max_length=30,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Nombre Dataset'}))
    parte_infectada=forms.CharField(max_length=30,required=False,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Parte infectada'}))
    color=forms.CharField(max_length=50,required=False,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Color'}))
    forma=forms.CharField(max_length=50,required=False,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Forma'}))
    localizacion=forms.CharField(max_length=50,required=False,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Localizacion'}))
    humedad=forms.CharField(max_length=50,required=False,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Humedad'}))
    enfermedad=forms.CharField(max_length=30,required=False,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Enfermedad'}))
    patogeno=forms.CharField(max_length=30,required=False,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Patógeno'}))
    referencia=forms.ModelChoiceField(Referencia.objects.all(),widget=forms.Select(attrs={
    'class': 'form-control '}))

class N_img(forms.Form):#form para la imagen de referencia 
    nombre=forms.CharField(max_length=30,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Nombre'}))
    img_org=forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    Data=forms.ModelChoiceField(Data.objects.all(),widget=forms.Select(attrs={
    'class': 'form-control'}))

class Form_Entrenamiento(forms.Form):
    nombre=forms.CharField(max_length=30,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Nombre'}))
    descripcion=forms.CharField(max_length=30,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Descripcion'}))
    #Iteraciones=forms.IntegerField(max_value=10,min_value=1,widget=forms.TextInput(attrs={
    #'class': 'form-control ', 'placeholder': 'Numero de iteraciones'}))
    umbral_minimo=forms.IntegerField(min_value=1,max_value=100,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Umbral minimo'}))
    umbral_par_media=forms.IntegerField(min_value=1,max_value=100,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Umbral de media y mediana'}))
    umbral_fusion=forms.IntegerField(min_value=1,max_value=100,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Umbral de fusión'}))
    umbral_poda=forms.IntegerField(min_value=15,max_value=90,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Umbral de poda'}))
    umbral_neuronas=forms.IntegerField(min_value=3,max_value=13,widget=forms.TextInput(attrs={
    'class': 'form-control ', 'placeholder': 'Numero de neuronas'}))
    canal1=forms.ChoiceField(choices=canales_status,widget=forms.Select(attrs={
    'class': 'form-control ', 'placeholder': 'Umbral de poda'}))
    canal2=forms.ChoiceField(choices=canales_status,widget=forms.Select(attrs={
    'class': 'form-control ', 'placeholder': 'Umbral de poda'}))
    canal3=forms.ChoiceField(choices=canales_status,widget=forms.Select(attrs={
    'class': 'form-control ', 'placeholder': 'Umbral de poda'}))
    canal4=forms.ChoiceField(choices=canales_status,widget=forms.Select(attrs={
    'class': 'form-control ', 'placeholder': 'Umbral de poda'}))
    datos=forms.ModelChoiceField(Data.objects.all(),widget=forms.Select(attrs={
    'class': 'form-control ', 'placeholder': 'Umbral de poda'}))
    
    

templates/entrenamiento/data_confirm_delete.html
{%extends "index1.html"%} {%block body%}
<form method="post">
    {% csrf_token %}
    <p><strong>¿Desea eliminar el registro: {{object}}?</strong></p>
    <button type="submit" class="btn btn-danger">Eliminar</button>
</form>
{%endblock body%}

templates/entrenamiento/entrenamiento_som_confirm_delete.html
{%extends "index1.html"%} {%block body%}
<form method="post">
    {% csrf_token %}
    <p><strong>¿Desea eliminar el registro: {{object}}?</strong></p>
    <button type="submit" class="btn btn-danger">Eliminar</button>
</form>
{%endblock body%}

templates/entrenamiento/listar_base.html
{%extends "index1.html"%} {% block body %}
<div style='text-align:center'>
    <h1 style=" color: white;">Listado de Bases</h1>
</div>
<div>
    <a href="{%url 'entrenamiento:imagen'%}" class="btn btn-primary">Subir Imagenes</a>
</div>
<div style="text-align: center;">
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for d in Dato%}
            <tr>
                <td>{{d.id_Data}}</td>
                <td>{{d.nombre}}</td>
                <td>
                    <a href="{%url 'entrenamiento:m_imgs' d.id_Data%}" class="btn btn-primary">Imagenes</a>
                    <a href="{%url 'entrenamiento:editar_data' d.id_Data%}" class="btn btn-primary">Editar</a>
                    <a href="{%url 'entrenamiento:eliminar_base' d.id_Data%}" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
            {%endfor%}
        </tbody>
    </table>

</div>
{% endblock body %}

templates/entrenamiento/listar_imagenes.html
{%extends "index1.html"%} {% block body %}
<div style="text-align: center;">
    <h1 style="color: white;">Listado de Imagenes</h1>
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Imagen</th>
            </tr>
        </thead>
        <tbody>
            {% for r in imgs%}
            <tr>
                <td>{{r.id_imagen}}</td>
                <td>{{r.nombre}}</td>
                <td><img src="../../media/{{r.imagen_normalizada}}" alt="Hola" width="200px"></td>
                <td><a href="{%url 'entrenamiento:elim_img' r.id_imagen%}" class="btn btn-danger">Eliminar</a></td>
            </tr>
            {%endfor%}
        </tbody>
    </table>

</div>
{% endblock body %}

templates/entrenamiento/listar_referencias.html
{%extends "index1.html"%} {% block body %}
<div style="text-align: center;">
    <h1 style="color: white;">Listado de Imagenes de referencia</h1>
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Imagen</th>
            </tr>
        </thead>
        <tbody>
            {% for r in referencias%}
            <tr>
                <td>{{r.id_ref}}</td>
                <td>{{r.nombre}}</td>
                <td><img src="../../media/{{r.img_normalizada}}" alt="Hola" width="200px"></td>
                <td><a href="{%url 'entrenamiento:eliminar_ref' r.id_ref%}" class="btn btn-danger">Eliminar</a></td>
            </tr>
            {%endfor%}
        </tbody>
    </table>

</div>
{% endblock body %}

templates/entrenamiento/menu.html
{%extends "index1.html"%} {% block body %}
<div id="contenido" class="form-group row justify-content-center">
    <div class="col-2">

    </div>
    <div class="col-8">
        <table class=" table table-dark">
            <thead>
                <tr>
                    <th>
                        <h3>Funciones Entrenamiento</h3>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Imagenes Refencias</td>
                    <td><a href="{%url 'entrenamiento:referencia'%}" class="btn btn-primary">Nueva</a></td>
                    <td><a href="{%url 'entrenamiento:mostrar_ref'%}" class="btn btn-primary">Mostrar</a></td>
                </tr>
                <tr>
                    <td>Formar Base para Entrenamiento</td>
                    <td><a href="{%url 'entrenamiento:nueva_base'%}" class="btn btn-primary">Nueva</a></td>
                    <td><a href="{%url 'entrenamiento:mostrar_data'%}" class="btn btn-primary">Mostrar</a></td>
                </tr>
                <tr>
                    <td>Entrenamiento mapa autoorganizado</td>
                    <td><a href="{%url 'entrenamiento:nuevo_entrenamiento'%}" class="btn btn-primary">Nuevo</a></td>
                    <td><a href="{%url 'entrenamiento:Mostrar_entrena'%}" class="btn btn-primary">Mostrar</a></td>
                </tr>
                <tr>
                    <td>Entrenamiento Red neuronal</td>
                    <td><a href="{%url 'red_neuronal:nueva_red'%}" class="btn btn-primary">Nueva</a></td>
                    <td><a href="{%url 'red_neuronal:mostrar'%}" class="btn btn-primary">Mostrar</a></td>
                </tr>
                <tr>
                    <td>Analisis de una imagen</td>
                    <td><a href="{%url 'analisis:nuevo'%}" class="btn btn-primary">Nueva</a></td>
                    <td><a href="{%url 'analisis:mostrar'%}" class="btn btn-primary">Mostrar</a></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="col-2">

    </div>
</div>



{%endblock body%}

templates/entrenamiento/menu_entre.html
{%extends "index1.html"%} {% block body %}
<div style="text-align: center;">
    <h1 style="color: white;">Listado de Entrenamientos</h1>
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Descripcion</th>
                <th>Umbrales</th>
                <th>Canal 1</th>
                <th>Canal 2</th>
                <th>Canal 3</th>
                <th>Canal 4</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for e in entre%}
            <tr>
                <td>{{e.id_Entrenamiento_Som}}</td>
                <td>{{e.nombre}}</td>
                <td>{{e.descripcion}}</td>
                <td>
                    <ul>
                        <li>Umbral Minimo</li>
                            <ul>
                                <li>{{e.umbral_minimo}}</li>
                            </ul>
                        <li>Umbral medias</li>
                            <ul>
                                <li>{{e.umbral_par_media}}</li>
                            </ul>
                        <li>Umbral fusion</li>
                            <ul>
                                <li>{{e.umbral_fusion}}</li>
                            </ul>
                        <li>Umbral Poda</li>
                            <ul>
                                <li>{{e.umbral_poda}}</li>
                            </ul>
                        <li>Umbral Neuronas</li>
                            <ul>
                                <li>{{e.umbral_neuronas}}</li>
                            </ul>
                    </ul>

                </td>
                <td>{{e.canal1}}</td>
                <td>{{e.canal2}}</td>
                <td>{{e.canal3}}</td>
                <td>{{e.canal4}}</td>
                <td>
                    <a href="{%url 'entrenamiento:m_imgs' e.id_Data.id_Data%}" class="btn btn-primary">Base</a>
                    <a href="{%url 'entrenamiento:Mostrar_n' e.id_Entrenamiento_Som%}" class="btn btn-primary">Neuronas</a>
                    <a href="{%url 'entrenamiento:Eliminar_entrena' e.id_Data.id_Data%}" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
            {%endfor%}
        </tbody>
    </table>

</div>
{% endblock body %}

templates/entrenamiento/neuronas.html
{%extends "index1.html"%} {% block body %}
<div style="text-align: center;">
    <h1 style="color: white;">Listado de Neuronas</h1>
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th>#</th>
                <th>Canal 1</th>
                <th>Canal 2</th>
                <th>Canal 3</th>
                <th>Canal 4</th>
                <th>Entrenamiento</th>
            </tr>
        </thead>
        <tbody>
            {% for n in Neurona%}
            <tr>
                <td>{{n.id_Neurons}}</td>
                <td>{{n.Canal1}}</td>
                <td>{{n.Canal2}}</td>
                <td>{{n.Canal3}}</td>
                <td>{{n.Canal4}}</td>
                <td>{{n.id_Entrenamiento_Som}}</td>
                </tr>
            {%endfor%}
        </tbody>
    </table>

</div>
{% endblock body %}

templates/entrenamiento/nueva_base.html
{%extends "index1.html"%} {%block body %}
<form method="POST" enctype="multipart/form-data" class="table-striped table-dark">
    {% csrf_token %} {%if error %}
    <h2> {{error}} </h2>
    {%endif%}
    <h1>Nueva Base de datos</h1>
    <div class="row">
        <div class="col">
            <h4>Nombre del Dataset</h4>
            {{form.nombre}}
            <h4>Parte infectada</h4>
            {{form.parte_infectada}}
            <h4>Color</h4>
            {{form.color}}
        </div>
        <div class="col">
            <h4>Forma</h4>
            {{form.forma}}
            <h4>Localizacion</h4>
            {{form.localizacion}}
            <h4>Humedad</h4>
            {{form.humedad}}
            <br>
            <br>
            <button type="submit" class="btn btn-primary btn-lg btn-block">Crear</button>
            <br>
        </div>
        <div class="col">
            <h4>Enfermedad</h4>
            {{form.enfermedad}}
            <h4>Patógeno</h4>
            {{form.patogeno}}
            <h4>Seleccione la imagen</h4>
            {{form.referencia}}
        </div>
    </div>
</form>
{% endblock body %}

templates/entrenamiento/nueva_imagen.html
{%extends "index1.html"%} {% block body %}
<div class="form-group row justify-content-center">
    <div class="col-3 ">
    </div>
    <div class="col-6 border border-dark rounded table-dark">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %} {%if error %}
            <script>
                alert('{{error}}')
            </script>
            {%endif%}
            <h1>Nueva Referencia</h1>
            <br>
            <h4>Nombre de la Imagen</h4>
            {{form.nombre}}
            <br>
            <h4>Seleccione la imagen</h4>
            {{form.img_org}}
            <br>
            <br>
            <h4>Seleccione la base</h4>
            {{form.Data}}
            <br>
            <br>
            <button type="submit" class="btn btn-primary">registrar</button><br>
            <br>
        </form>
    </div>
    <div class="col-3 ">

    </div>

</div>
{% endblock body %}

templates/entrenamiento/nuevo.html
{%extends "index1.html"%} {% block body %}
<div class="form-group row justify-content-center">
    <div class="col-3 ">
    </div>
    <div class="col-6 border border-dark rounded table-dark">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %} {%if error %}
            <script>
                alert('Tipo de Dato no permitido')
            </script>
            {%endif%}
            <h1>Nueva Referencia</h1>
            <br>
            <h4>Nombre de la Imagen</h4>
            {{form.nombre}}
            <br>
            <h4>Seleccione la imagen</h4>
            {{form.img_ref}}
            <br>
            <br>
            <button type="submit" class="btn btn-primary">registrar</button><br>
            <br>
        </form>
    </div>
    <div class="col-3 ">

    </div>

</div>
{% endblock body %}

templates/entrenamiento/nuevo_entrenamiento.html
{%extends "index1.html"%} {%block body %}

<h3 style="text-align:center">Nuevo entrenamiento</h3>
{%if error or num%}
    <div class="alert alert-danger" role="alert">
        {{error}}
        {%if num%}
        <ul class="errorlist">
            <li>Canales</li>
            <ul class="errorlist">
                <li>Seleccione canales diferentes</li>
            </ul>
        </ul>
        {%endif%}
    </div>
{%endif%}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row border border-dark rounded table-dark">
      <div class="col">
          <label for="id_nombre">Nombre del entrenamiento</label>
          {{form.nombre}}
          <label for="id_descripcion">Descripcion del entrenamiento</label>
          {{form.descripcion}}
          <Label for="id_Data">Seleccione la base de datos</Label>
          {{form.datos}}
          <br>
      </div>
      <div class="col">
          <label for="id_umbral_minimo">Umbral Minimo</label>
          {{form.umbral_minimo}}
          <label for="id_umbral_par_medias">Umbral de medias</label>
          {{form.umbral_par_media}}
          <label for="id_umbral_fusion">Umbral de fusión de neuronas</label>
          {{form.umbral_fusion}}
          <label for="id_umbral_minimo">Umbral de poda de neuronas</label>
          {{form.umbral_poda}}
          <label for="id_umbral_minimo">Cantidad maxima de neuronas a generar</label>
          {{form.umbral_neuronas}}
          <br>
          <br>
          <button type="submit" class="btn btn-primary btn-lg btn-block">registrar</button><br>
      </div>
      <div class="col">
        <label for="id_canal1">Ingrese valor del canal 1</label>
        {{form.canal1}}
        <label for="id_canal2">Ingrese valor del canal 2</label>
        {{form.canal2}}
        <label for="id_canal3">Ingrese valor del canal 3</label>
        {{form.canal3}}
        <label for="id_canal4">Ingrese valor del canal 4</label>
        {{form.canal4}}
      </div>
    </div>
  </form>
{% endblock body %}

templates/entrenamiento/prueba.html
{%extends "index.html"%} {% block body %}
<table class='table  table-bordered table-dark'>
    <thead>
        <tr>
            <th>
                <h2>Imagenes</h2>
            </th>
            <th>
                <h2>Selección</h2>
            </th>
        </tr>
    </thead>
    <tbody>
        {%for imagen in img%}
        <tr>
            <td><img src="../../media/{{imagen}}" alt="error" width="400" height="400"></td>
            <td><input type="checkbox" name="imagen" id="imagen"></td>
        </tr>
        {%endfor%}
    </tbody>
</table>

<p>
    <p>
        <input type="button" value="enviar" class='btn btn-outline-primary btn-lg'>
    </p>
</p> {% endblock body %}

templates/entrenamiento/referencia_confirm_delete.html
{%extends "index1.html"%} {%block body%}
<form method="post">
    {% csrf_token %}
    <p><strong>¿Desea eliminar el registro: {{object}}?</strong></p>
    <button type="submit" class="btn btn-danger">Eliminar</button>
</form>
{%endblock body%}